### ISSUE TITLE
Error with word2DITA transform

### ISSUE THREAD

**Issue by mtooke** [dita4publishers/d4p-word2dita#3]
I've run into the following error message:

```
 [xslt]  + [INFO] ====================================
 [xslt]  + [INFO] Doing general simpleWpDoc fixup....
 [xslt]  + [INFO] ====================================
 [xslt]  + [DEBUG] Fixed-up simple WP doc saved as file:/C:/ditawork/all_defaults/dita/simpleWpDocFixup.xml
 [xslt] C:\ditawork\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\wordml2simpleAddLevels.xsl:53: Fatal Error! Cannot switch to a final result destination while writing a temporary tree
 [xslt] Failed to process C:\ditawork\all_defaults\word\temp\temp20150603152420971\word2bookmap_test_01\word\document.xml
```

I hit this with a fresh install of the OT, with both 0.9.19 and 1.0 RC 9 of the d4p plugin. Tried on my own docx files and the sample.

Some other parts of the log:

initProperties:
     [echo] +++ word2dita-specific properties:
     [echo] #Ant properties
     [echo] #Wed Jun 03 15:24:21 EDT 2015
     [echo] w2d.base.dir=C:\ditawork\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita
     [echo] w2d.clean.output.dir=true
     [echo] w2d.debug.xslt=true
     [echo] w2d.defaultStyleToTagMap=C:\ditawork\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\word-builtin-styles-style2tagmap.xml
     [echo] w2d.generate.navtitles=true
     [echo] w2d.have.word.doc=true
     [echo] w2d.language=en-US
     [echo] w2d.out.dir=C:\ditawork\all_defaults\dita
     [echo] w2d.root.map.name=word2bookmap_test_01
     [echo] w2d.root.output.filename=word2bookmap_test_01.ditamap
     [echo] w2d.style-to-tag-map=C:\ditawork\all_defaults\word\style2tagmap.xml
     [echo] w2d.temp.dir=C:\ditawork\all_defaults\word\temp\temp20150603152420971
     [echo] w2d.topic.extension=.dita
     [echo] w2d.word2dita.xslt=C:\ditawork\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl
     [echo] w2p.do.clean.output.dir=true

...

transformWordToDita:
     [echo] [INFO] Creating output directory C:\ditawork\all_defaults\dita...
     [echo] [INFO] Creating output file word2bookmap_test_01.ditamap...
     [echo] [INFO] Generating DITA documents from Word document in output directory C:\ditawork\all_defaults\dita...
     [echo] [INFO]   Using XSLT C:\ditawork\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl...
     [xslt] Processing C:\ditawork\all_defaults\word\temp\temp20150603152420971\word2bookmap_test_01\word\document.xml to C:\ditawork\all_defaults\dita\word2bookmap_test_01.ditamap
     [xslt] Loading stylesheet C:\ditawork\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl
     [xslt]  
     [xslt]       ==========================================
     [xslt]       DOCX 2 DITA
     [xslt]  
     [xslt]       Version: ^version^ - build ^buildnumber^ at ^timestamp^
     [xslt]  
     [xslt]       Parameters:
     [xslt]  
     [xslt]       + styleMapUri     = "file:/C:/ditawork/all_defaults/word/style2tagmap.xml"
     [xslt]       + mediaDirUri     = "file:/C:/ditawork/all_defaults/dita/topics/media"  
     [xslt]       + rootMapName     = "word2bookmap_test_01"
     [xslt]       + rootTopicName   = ""
     [xslt]       + submapNamePrefix= "map"  
     [xslt]       + rootMapUrl      = "word2bookmap_test_01.ditamap"
     [xslt]       + rootTopicUrl    = ""
     [xslt]       + topicExtension  = ".dita"
     [xslt]       + fileNamePrefix  = ""  
     [xslt]       + filterBr        = "false"  
     [xslt]       + filterTabs      = "false"  
     [xslt]       + language        = "en-US"  
     [xslt]       + outputDir       = "file:/C:/ditawork/all_defaults/dita/"  
     [xslt]       + debug           = "true"
     [xslt]       + includeWordBackPointers= "true"  
     [xslt]       + chartsAsTables  = "false"  
     [xslt]       + saveIntermediateDocs  = "false"  
     [xslt]  
     [xslt]       Global Variables:
     [xslt]  
     [xslt]       + platform         = "windows"
     [xslt]       + debugBoolean     = "true"
     [xslt]       + doSaveIntermediateDocs = "true"

Thanks again!

**Comment by mtooke** [comment]
Has anybody been able to reproduce this one? Any idea what causes it?

**Comment by drmacro** [comment]
I haven't had a chance to look at this. Did you create a gist with sample data that I can use to try to reproduce the problem?

**Comment by drmacro** [comment]
I see the cause of the problem--it will happen if debugging is turned on.

But, it _shouldn't_ happen, in that the code has been carefully written to avoid this very problem. So the fact that it is happening means there must be some unexpected interaction between your source document, style-to-tag mapping, and the code that is processing them.

The workaround is to turn debugging off: set the w2d.debug.xslt parameter to "false" (it's set to false by default but your log shows it's been set to "true". 

But I still need to understand the cause of the problem. Either there's a logic bug in the generation code or I'm not detecting and reporting a misconfiguration of the style-to-tag map.

**Comment by mtooke** [comment]
When I set debugging off, I get this:

C:\ditawork\build>ant -f myword2dita.xml
Unable to locate tools.jar. Expected to find it in C:\Program Files\Java\jre1.8.0_45\lib\tools.jar
Buildfile: C:\ditawork\build\myword2dita.xml

transformMyDoc:

d4p.wordToDita.init:

wordToDita:
     [echo] [DEBUG] wordToDita.dir=C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita

checkWordDoc:

checkParameters:

initProperties:
     [echo] +++ word2dita-specific properties:
     [echo] #Ant properties
     [echo] #Mon Jun 15 11:37:32 EDT 2015
     [echo] w2d.base.dir=C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita
     [echo] w2d.clean.output.dir=true
     [echo] w2d.debug.xslt=false
     [echo] w2d.defaultStyleToTagMap=C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\xsl\word-builtin-styles-style2tagmap.xml
     [echo] w2d.generate.navtitles=true
     [echo] w2d.have.word.doc=true
     [echo] w2d.include.word.backpointers=false
     [echo] w2d.language=en-US
     [echo] w2d.out.dir=c:\ditawork\ditaout\w2d
     [echo] w2d.root.output.filename=Test.ditamap
     [echo] w2d.root.topic.name=Test.ditamap
     [echo] w2d.style-to-tag-map=C:\ditawork\DITA-OT1.7.5\plugins\net.sourceforge.dita4publishers.word2dita\xsl\sample_tagmap.xml
     [echo] w2d.temp.dir=C:\ditawork\build\temp\temp20150615113730847
     [echo] w2d.topic.extension=.dita
     [echo] w2d.word2dita.xslt=C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl
     [echo] w2p.do.clean.output.dir=true

doWord2Dita:
    [mkdir] Created dir: C:\ditawork\build\temp\temp20150615113730847

unzipWordDoc:
    [unzip] Expanding: C:\ditawork\wrdsrc\Test.docx into C:\ditawork\build\temp\temp20150615113730847\Test
     [echo] w2d.style-to-tag-map='C:\ditawork\DITA-OT1.7.5\plugins\net.sourceforge.dita4publishers.word2dita\xsl\sample_tagmap.xml'

cleanOutputDir:
     [echo] [INFO] Cleaning output directory c:\ditawork\ditaout\w2d...

transformWordToDita:
     [echo] [INFO] Creating output directory c:\ditawork\ditaout\w2d...
     [echo] [INFO] Creating output file Test.ditamap...

BUILD FAILED
C:\ditawork\build\myword2dita.xml:24: The following error occurred while executing this line:
C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\build_transtype-word2dita.xml:28: The following error occurred while executing this line:
C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\build-word2dita.xml:166: The following error occurred while executing this line:
C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\build-word2dita.xml:200: A source file is missing :C:\ditawork\DITA-OT1.7.5\plugins\net.sourceforge.dita4publishers.word2dita\xsl\sample_tagmap.xml

Total time: 3 seconds

This file is not in my plugin.

Can you tell me which version of the d4p plugin to use? I'm currently using dita4publishers-html5-toolkit-plugins-1.0.0RC09.zip. It looks like the word2dita plugins aren't including in any zip file after this one?

**Comment by drmacro** [comment]
I'm in the process of moving the Word2DITA stuff to its own top-level project since it's often used without the need for any of the other D4P stuff but I haven't completed it. 

I've updated the RC13 D4P release with a new Word2DITA package that should be what you're looking for:

https://github.com/dita4publishers/dita4publishers/releases/download/1.0.0RC13/dita4publishers-word2dita-plugins-1.0.0RC13.zip

**Comment by drmacro** [comment]
But it also looks like you might have a bad local configuration. 

I would recommend creating a clean OT install and then adding just the plugins from this new Word2DITA package, plus whatever plugins you maintain yourself (e.g., your local doctype shells or whatever).

**Comment by mtooke** [comment]
Thanks Elliot.

The latest zip you pointed to has nothing in this folder:

dita4publishers-word2dita-plugins-1.0.0RC13.zip\org.dita4publishers.word2dita\org.dita-community.common.xslt\

After I copied the contents of that subfolder from a previous download, and I turn off debug, I get this error:

```
 [xslt]  + [INFO]
 [xslt]  + [INFO] ++++++++++++++++++++++++++++++
 [xslt]  + [INFO] simple2dita: Phase 1: Generate DITA maps and topics as a single XML document....
 [xslt] C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\xsl\simple2dita.xsl:158: Fatal Error! An empty sequence is not allowed as the second argument of relpath:newFile()
 [xslt] Failed to process C:\ditawork\all_defaults\word\temp\temp20150615152112184\word2bookmap_test_01\word\document.xml
```

BUILD FAILED
C:\ditawork\all_defaults\word\dita-ot-run-word2dita.xml:24: The following error occurred while executing this line:
C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\build_transtype-word2dita.xml:28: The following error occurred while executing this line:
C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\build-word2dita.xml:166: The following error occurred while executing this line:
C:\ditawork\DITA-OT1.7.5\plugins\org.dita4publishers.word2dita\build-word2dita.xml:210: Fatal error during transformation

Total time: 2 seconds

Just to reset, I'm running your sample from all_defaults\word\dita-ot-run-word2dita.xml. I haven't changed any of the mappings or any of the config.

**Comment by drmacro** [comment]
I just downloaded the zip again and verified that the org.dita-community.common.xslt plugin has all its files, so not sure why you wouldn't be seeing them. 

The message you indicate was a bug that was fixed, perhaps more recently than RC09

![rc13-unzipped](https://cloud.githubusercontent.com/assets/1004229/8168979/38da2296-136c-11e5-8376-7296a6000cbd.png)

**Comment by mtooke** [comment]
It's missing from

dita4publishers-word2dita-plugins-1.0.0RC13\org.dita4publishers.word2dita\org.dita-community.common.xslt

not:

dita4publishers-word2dita-plugins-1.0.0RC13\org.dita-community.common.xslt

My first build was complaining because it couldn't find relpath_util.xsl in org.dita4publishers.word2dita\org.dita-community.common.xslt\xsl\ .

This may be the problem...

**Comment by drmacro** [comment]
I see the problem--the relative path in docx2dita.xsl is wrong.

You can fix it locally by changing line 13 to:

```
  <xsl:import href="../../org.dita-community.common.xslt/xsl/relpath_util.xsl"/>
```

I'll fix the code and recreate the package

**Comment by drmacro** [comment]
OK, I've corrected teh code and updated the RC13 zip under the main dita4publishers RC3 release.

**Comment by mtooke** [comment]
Sorry Elliot. That doesn't fix the error I get below:

```
 [xslt]  + [INFO]
 [xslt]  + [INFO] simple2dita: Processing intermediate simpleML XML to generate DITA XML...
 [xslt]  + [INFO]
 [xslt]  + [INFO] ++++++++++++++++++++++++++++++
 [xslt]  + [INFO] simple2dita: Phase 1: Generate DITA maps and topics as a single XML document....
 [xslt] C:\ditawork\test\plugins\org.dita4publishers.word2dita\xsl\simple2dita.xsl:158: Fatal Error! An empty sequence is not allowed as the second argument of relpath:newFile()
 [xslt] Failed to process C:\ditawork\all_defaults\word\temp\temp20150616090558495\word2bookmap_test_01\word\document.xml
```

BUILD FAILED
C:\ditawork\all_defaults\word\dita-ot-run-word2dita.xml:24: The following error occurred while executing this line:
C:\ditawork\test\plugins\org.dita4publishers.word2dita\build_transtype-word2dita.xml:28: The following error occurred while executing this line:
C:\ditawork\test\plugins\org.dita4publishers.word2dita\build-word2dita.xml:166: The following error occurred while executing this line:
C:\ditawork\test\plugins\org.dita4publishers.word2dita\build-word2dita.xml:210: Fatal error during transformation

I've tried this with fresh installs of 1.7.5 and 1.8.5 (just to see if it made a difference). I'm wondering if it's the sample project. Is there any way I can zip it and send it to you to see if you can replicate this?

**Comment by mtooke** [comment]
Hi Elliot,

Sorry to keep beating you to death with this but I'm getting a bit desperate. Is there a sample app that you know works that you can point me to, or can I send you the sample I'm using to see if it works on your end? I'm using the all_defaults/word sample and AFAIK I haven't changed anything.

Thanks

**Comment by drmacro** [comment]
Sorry, I had to attend to a critical issue with the adjust-copy-to plugin and all the main transforms that depended on it that took the last 3 days to resolve. I'll look at this this morning.

I'll take a look this morning.

**Comment by drmacro** [comment]
OK, I've reproduced the failure using the w2d_test-default-styles-to-maps-and-topics.docx

**Comment by drmacro** [comment]
OK, the issue is that the root topic name parameter must be specified the XSLT process. The base Ant script is supposed to ensure that the value is set if you don't set it explicitly, but for some reason it's not working.

The workaround is the set the value yourself, e.g.:

```
ant -f mybuild.xml -Ddita-ot-dir=`pwd` -Dw2d.root.topic.name=rootTopic
```

I'll figure out why the Ant script is not doing the right thing. I'll also make the XSLT code not break when the value isn't specified (by making the default root topic name be the same as the root map name if it's specified or setting some useful default value.

**Comment by drmacro** [comment]
OK, I've pushed some code change to the org.dita4publishers.word2dita develop branch--can you download a Zip of that and see if it resolves your problem? I have more testing to do but it might work.

Also, I realized that the word-builtin-styles-style2tagmap.xml style-to-tag map had not been migrated to the new style-to-tag map markup. I've corrected that in the plugin.

But if you haven't already, you should migrate your style-to-tag map using the org.dita4publishers.word2dita/utils/style2tagmapMigrator.xsl transform--it takes the style-to-tag map as input and produces a new version reflecting the new markup. The transform doesn't require any parameters or anything.

**Comment by mtooke** [comment]
Thanks Eliot! That seems to work I think.

I updated, then grabbed the dita4-publishers.zip from github and used the
samples in there. I think I was using the a sample from the old sourceforge
site, which may have been part of the problem.

I'm running the default-styles-to-maps-topics test. It trips the failures
(it's looking for another level of nesting in topic names) but when I
comment them out, everything seems kosher.

Thanks again!

Morley

**Comment by mtooke** [comment]
BTW - this is working fantastic for me. Much better than I could have expected. Great job! Thanks again.

**Comment by drmacro** [comment]
Cool--glad we were able to make it work.
